"""empty message

Revision ID: 0456df43f272
Revises: f7824d41b81d
Create Date: 2019-11-30 16:51:30.733317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0456df43f272'
down_revision = 'f7824d41b81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameterSettings', sa.Column('sessionActive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameterSettings', 'sessionActive')
    # ### end Alembic commands ###
