"""empty message

Revision ID: 1b9a407505e8
Revises: 88456daca88f
Create Date: 2019-11-29 17:38:56.775933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9a407505e8'
down_revision = '88456daca88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additionalQuestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response1', sa.String(length=500), nullable=True),
    sa.Column('response2', sa.String(length=500), nullable=True),
    sa.Column('response3', sa.String(length=500), nullable=True),
    sa.Column('idAccount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAccount'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additionalQuestion')
    # ### end Alembic commands ###
