"""empty message

Revision ID: 1e058ea7b09b
Revises: e90d872debba
Create Date: 2019-10-02 11:39:54.931668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e058ea7b09b'
down_revision = 'e90d872debba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.drop_column('product', 'id_salesrecord')
    op.add_column('salesrecord', sa.Column('id_product', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salesrecord', 'product', ['id_product'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salesrecord', type_='foreignkey')
    op.drop_column('salesrecord', 'id_product')
    op.add_column('product', sa.Column('id_salesrecord', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('product_ibfk_1', 'product', 'salesrecord', ['id_salesrecord'], ['id'])
    # ### end Alembic commands ###
