"""empty message

Revision ID: 2ac70e4ece48
Revises: 4cd295be940d
Create Date: 2019-10-08 17:09:27.527611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac70e4ece48'
down_revision = '4cd295be940d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securityQuestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securityQuestion')
    # ### end Alembic commands ###
