"""empty message

Revision ID: 4157caf7ac0a
Revises: 2ac70e4ece48
Create Date: 2019-10-24 23:44:35.619000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4157caf7ac0a'
down_revision = '2ac70e4ece48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('idClient', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'client', ['idClient'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'idClient')
    # ### end Alembic commands ###
