"""empty message

Revision ID: 586b55462f6c
Revises: c6150ed5fe57
Create Date: 2019-11-09 18:19:35.874488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586b55462f6c'
down_revision = 'c6150ed5fe57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('share', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'share')
    # ### end Alembic commands ###
