"""empty message

Revision ID: 5e1d05c7f589
Revises: 
Create Date: 2019-11-16 13:44:53.738224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1d05c7f589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('idBankAccount', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'bankAccount', ['idBankAccount'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'idBankAccount')
    op.drop_column('transaction', 'active')
    # ### end Alembic commands ###
