"""empty message

Revision ID: 88456daca88f
Revises: 
Create Date: 2019-11-24 21:56:07.959208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88456daca88f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'minimumLoan')
    op.drop_column('campaign', 'minimumPeriod')
    op.drop_column('campaign', 'maximumLoan')
    op.drop_column('campaign', 'maximumPeriod')
    op.drop_column('campaign', 'interestRate')
    op.add_column('lead', sa.Column('interestRate', sa.Float(), nullable=True))
    op.add_column('lead', sa.Column('maximumPeriod', sa.Integer(), nullable=True))
    op.add_column('lead', sa.Column('minimumPeriod', sa.Integer(), nullable=True))
    op.add_column('loan', sa.Column('idLead', sa.Integer(), nullable=True))
    op.drop_constraint('loan_ibfk_2', 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'lead', ['idLead'], ['id'])
    op.drop_column('loan', 'idCampaign')
    op.add_column('person', sa.Column('gender', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'gender')
    op.add_column('loan', sa.Column('idCampaign', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key('loan_ibfk_2', 'loan', 'campaign', ['idCampaign'], ['id'])
    op.drop_column('loan', 'idLead')
    op.drop_column('lead', 'minimumPeriod')
    op.drop_column('lead', 'maximumPeriod')
    op.drop_column('lead', 'interestRate')
    op.add_column('campaign', sa.Column('interestRate', mysql.FLOAT(), nullable=True))
    op.add_column('campaign', sa.Column('maximumPeriod', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('maximumLoan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('minimumPeriod', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('minimumLoan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
