"""empty message

Revision ID: 8d10a550d5ae
Revises: 
Create Date: 2019-11-11 01:44:03.847197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d10a550d5ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('commission', sa.Float(), nullable=True))
    op.add_column('parameterSettings', sa.Column('commissionPercentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameterSettings', 'commissionPercentage')
    op.drop_column('loan', 'commission')
    # ### end Alembic commands ###
