"""empty message

Revision ID: c6150ed5fe57
Revises: 05cf6a20712f
Create Date: 2019-11-07 00:42:34.966051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6150ed5fe57'
down_revision = '05cf6a20712f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameterSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maxTokenSends', sa.Integer(), nullable=True),
    sa.Column('maxDiaryMovements', sa.Integer(), nullable=True),
    sa.Column('legalAge', sa.Integer(), nullable=True),
    sa.Column('maxAccountsNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shareType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountNumber', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('idCurrency', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurrency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('month', sa.String(length=255), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('minimumLoan', sa.Integer(), nullable=True),
    sa.Column('maximumLoan', sa.Integer(), nullable=True),
    sa.Column('minimumPeriod', sa.Integer(), nullable=True),
    sa.Column('maximumPeriod', sa.Integer(), nullable=True),
    sa.Column('interestRate', sa.Integer(), nullable=True),
    sa.Column('idCurrency', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurrency'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimumLoan', sa.Integer(), nullable=True),
    sa.Column('maximumLoan', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('idCampaign', sa.Integer(), nullable=True),
    sa.Column('idClient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCampaign'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['idClient'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('totalShares', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('interestRate', sa.Integer(), nullable=True),
    sa.Column('idCampaign', sa.Integer(), nullable=True),
    sa.Column('idClient', sa.Integer(), nullable=True),
    sa.Column('idSalesRecord', sa.Integer(), nullable=True),
    sa.Column('idShareType', sa.Integer(), nullable=True),
    sa.Column('idAccount', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAccount'], ['account.id'], ),
    sa.ForeignKeyConstraint(['idCampaign'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['idClient'], ['client.id'], ),
    sa.ForeignKeyConstraint(['idSalesRecord'], ['salesRecord.id'], ),
    sa.ForeignKeyConstraint(['idShareType'], ['shareType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('lead')
    op.drop_table('campaign')
    op.drop_table('bankAccount')
    op.drop_table('shareType')
    op.drop_table('parameterSettings')
    # ### end Alembic commands ###
