"""empty message

Revision ID: c98c049ad60f
Revises: c6fdd65e3921
Create Date: 2019-09-30 06:25:23.578833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98c049ad60f'
down_revision = 'c6fdd65e3921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=True),
    sa.Column('currency_symbol', sa.String(length=5), nullable=True),
    sa.Column('currenty_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_name'),
    sa.UniqueConstraint('currency_symbol'),
    sa.UniqueConstraint('currenty_code')
    )
    op.add_column('account', sa.Column('id_currency', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'currency', ['id_currency'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'id_currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
