"""empty message

Revision ID: d7d174ead8d7
Revises: 
Create Date: 2019-10-05 18:53:24.739014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d174ead8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklistClassification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencyName', sa.String(length=100), nullable=True),
    sa.Column('currencySymbol', sa.String(length=5), nullable=True),
    sa.Column('currencyCode', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currencyCode'),
    sa.UniqueConstraint('currencyName'),
    sa.UniqueConstraint('currencySymbol')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documentType', sa.String(length=100), nullable=True),
    sa.Column('documentNumber', sa.String(length=20), nullable=True),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('middleName', sa.String(length=100), nullable=True),
    sa.Column('fatherLastname', sa.String(length=100), nullable=True),
    sa.Column('motherLastname', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('vehicle1Plate', sa.String(length=100), nullable=True),
    sa.Column('vehicle2Plate', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documentNumber')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge')
    )
    op.create_table('recordStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountNumber', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('openingDate', sa.DateTime(), nullable=True),
    sa.Column('closingDate', sa.DateTime(), nullable=True),
    sa.Column('cardNumber', sa.String(length=100), nullable=True),
    sa.Column('idAccountType', sa.Integer(), nullable=True),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('idCurrency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAccountType'], ['accountType.id'], ),
    sa.ForeignKeyConstraint(['idCurrency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['idProduct'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accountNumber')
    )
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documentType', sa.String(length=100), nullable=True),
    sa.Column('documentNumber', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('idBlacklistClassification', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idBlacklistClassification'], ['blacklistClassification.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documentNumber')
    )
    op.create_table('prospectiveClient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastEnterDate', sa.DateTime(), nullable=True),
    sa.Column('enterCount', sa.Integer(), nullable=True),
    sa.Column('email1', sa.String(length=100), nullable=True),
    sa.Column('email2', sa.String(length=100), nullable=True),
    sa.Column('cellphone1', sa.String(length=20), nullable=True),
    sa.Column('cellphone2', sa.String(length=20), nullable=True),
    sa.Column('idPerson', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPerson'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('idProfile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProfile'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registerDate', sa.DateTime(), nullable=True),
    sa.Column('totalAccounts', sa.Integer(), nullable=True),
    sa.Column('activeLoans', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('idProspectiveClient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProspectiveClient'], ['prospectiveClient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('idAccount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAccount'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salesRecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('requestDate', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('idRecordStatus', sa.Integer(), nullable=True),
    sa.Column('idClient', sa.Integer(), nullable=True),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idClient'], ['client.id'], ),
    sa.ForeignKeyConstraint(['idProduct'], ['product.id'], ),
    sa.ForeignKeyConstraint(['idRecordStatus'], ['recordStatus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salesRecord')
    op.drop_table('transaction')
    op.drop_table('client')
    op.drop_table('user')
    op.drop_table('prospectiveClient')
    op.drop_table('blacklist')
    op.drop_table('account')
    op.drop_table('recordStatus')
    op.drop_table('profile')
    op.drop_table('product')
    op.drop_table('person')
    op.drop_table('currency')
    op.drop_table('blacklistClassification')
    op.drop_table('accountType')
    # ### end Alembic commands ###
