"""empty message

Revision ID: e90d872debba
Revises: 1031b53f7c13
Create Date: 2019-10-02 10:23:02.903187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90d872debba'
down_revision = '1031b53f7c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('father_lastname', sa.String(length=100), nullable=True),
    sa.Column('mother_lastname', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('vehicle1_plate', sa.String(length=100), nullable=True),
    sa.Column('vehicle2_plate', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('prospectiveclient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_enter_date', sa.DateTime(), nullable=True),
    sa.Column('enter_count', sa.Integer(), nullable=True),
    sa.Column('email1', sa.String(length=100), nullable=True),
    sa.Column('email2', sa.String(length=100), nullable=True),
    sa.Column('cellphone1', sa.String(length=20), nullable=True),
    sa.Column('cellphone2', sa.String(length=20), nullable=True),
    sa.Column('id_person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('active_loans', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id_prospectiveclient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prospectiveclient'], ['prospectiveclient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('salesrecord', sa.Column('id_client', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salesrecord', 'client', ['id_client'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salesrecord', type_='foreignkey')
    op.drop_column('salesrecord', 'id_client')
    op.drop_table('client')
    op.drop_table('prospectiveclient')
    op.drop_table('person')
    # ### end Alembic commands ###
