"""empty message

Revision ID: f7824d41b81d
Revises: 1b9a407505e8
Create Date: 2019-11-29 19:41:20.392949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7824d41b81d'
down_revision = '1b9a407505e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additionalQuestion', sa.Column('response4', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additionalQuestion', 'response4')
    # ### end Alembic commands ###
